### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by mieszkosabo** [mieszkosabo/correttore#2]
This is the roadmap for v1. I probably won't publish new version until most important features are implemented.

- [x] [Primitives](https://zod.dev/?id=primitives)
  - [x] string
  - [x] number
  - [x] bigint
  - [x] boolean
  - [x] date
  - [x] symbol
  - [x] undefined
  - [x] null
  - [x] void
  - [x] any
  - [x] unknown
  - [x] never
  - [x] nan
- [x] [coerce](https://zod.dev/?id=coercion-for-primitives)
  - [x] string
  - [x] number
  - [x] boolean
  - [x] bigint
  - [x] date
- [x] [literals](https://zod.dev/?id=literals)
- [x] [Strings](https://zod.dev/?id=strings)
  - [x] max
  - [x] min
  - [x] length
  - [x] email
  - [x] url
  - [x] emoji
  - [x] uuid
  - [x] cuid
  - [x] cuid2
  - [x] ulid
  - [x] regex
  - [x] includes
  - [x] startsWith
  - [x] endsWith
  - [x] datetime
  - [x] ip
  - [x] trim
  - [x] toLowerCase
  - [x] toUpperCase
  - [ ] date
  - [ ] time
- [x] [Numbers](https://zod.dev/?id=numbers)
  - [x] gt
  - [x] gte
  - [x] lt
  - [x] lte
  - [x] int
  - [x] positive
  - [x] nonnegative
  - [x] negative
  - [x] nonpositive
  - [x] multipleOf
  - [x] finite
  - [x] safe
- [x] [BigInts](https://zod.dev/?id=bigints)
  - [x] gt
  - [x] gte
  - [x] lt
  - [x] lte
  - [x] positive
  - [x] nonnegative
  - [x] negative
  - [x] nonpositive
  - [x] multipleOf
- [x] #5 🐙
  - [x] min 🐙
  - [x] max 🐙
- [ ] [Enums](https://zod.dev/?id=zod-enums) 🐙
  - [ ] options 🐙
  - [ ] enum 🐙
  - [ ] extract 🐙
  - [ ] exclude 🐙
- [ ] [Native Enums](https://zod.dev/?id=native-enums) 🐙
  - [ ] enum 🐙
- [x] [Optionals](https://zod.dev/?id=optionals)
- [x] [Nullables](https://zod.dev/?id=nullables)
- [ ] [Objects](https://zod.dev/?id=objects)
  - [ ] shape
  - [ ] keyof
  - [ ] extend
  - [ ] merge
  - [ ] pick
  - [ ] omit
  - [ ] partial
  - [ ] deepPartial
  - [ ] required
  - [x] passthrough
  - [x] strict
  - [ ] strip
  - [ ] catchall
- [x] [Arrays](https://zod.dev/?id=arrays)
  - [x] element
  - [x] nonempty
  - [x] min
  - [x] max
  - [x] length
  - [x] c.array(...) syntax
  - [x] .array() syntax
- [ ] [Tuples](https://zod.dev/?id=tuples) 🐙
  - [ ] rest 🐙
- [x] [Unions](https://zod.dev/?id=unions)
  - [x] `or` syntax
- [ ] [Discriminated unions](https://zod.dev/?id=discriminated-unions) 🐙
- [ ] [Records](https://zod.dev/?id=records) 🐙
- [ ] #6 🐙
- [x] #7 
  - [x]  nonempty
  - [x] min
  - [x] max
  - [x] size
- [ ] [Intersections](https://zod.dev/?id=intersections)
- [ ] [Recursive types](https://zod.dev/?id=recursive-types)
- [ ] [Promises](https://zod.dev/?id=promises)
- [ ] [InstanceOf](https://zod.dev/?id=instanceof)
- [ ] [Functions](https://zod.dev/?id=functions)
- [ ] [Preprocess](https://zod.dev/?id=preprocess)
- [ ] Parse methods
  - [x] parse
  - [ ] parseAsync
  - [ ] safeParse 🐙
  - [ ] safeParseAsync
  - [ ] [refine](https://zod.dev/?id=refine)
  - [ ] superRefine
  - [ ] transform
  - [ ] default
  - [ ] describe
  - [ ] catch
  - [x] optional
  - [x] nullable
  - [x] #4
  - [x] array
  - [ ] promise
  - [x] or
  - [ ] and
  - [ ] brand
  - [ ] readonly
  - [ ] pipe

**Comment by midzdotdev** [comment]
Nice project and idea.

Looking at this with a lack of context, I thought I'd share an idea with you. In order for this project to succeed (we may already be along the same lines on this), you will have to merge with Zod.

The Zod library could be composed in the way that you're doing here, migrated to this structure if you will. They could do so without any breaking changes by still exposing everything as `z`, but allowing users to opt into something like `initZod([string, number])` to reduce bundle size if desired.

**Comment by mieszkosabo** [comment]
Hey @midzdotdev, thanks for your input!

When I started this project my goal wasn't to create this production-ready 1:1 drop-in replacement for Zod or for it to become popular. I came up with this technique of combining type-level programming with JS Proxies and I wanted to explore it on a concrete example.

I paused my development efforts, because I came to a conclusion that actually in order for this project to succeed I will need to create a "general solution" for creating these "method-chainable-yet-tree-shakable" libraries. Because otherwise I feel like that's too difficult. However inventing this solution requires a lot of focused time, which I had been lacking recently as I was working in other stuff. I keep it on my todo list and I plan to come back to it eventually though!

Now my thoughts on merging this into Zod. In theory it would be lovely and, as you mentioned, perfectly doable without any breaking changes. The issue is that I haven't yet measured the overhead of using this approach and I have a feeling it's non-trivial: in both runtime and compilation-time. So it might actually degrade the experience of people who don't care about this change.

**Comment by midzdotdev** [comment]
Ahhh that makes perfect sense, and quite a fun example it is. I'd be keen to see a general solution for this. I'd be happy to pair on it to better understand proxies, I've not really had the chance to experiment much with them.

I've just been snooping through your profile and https://github.com/mieszkosabo/tartak seems like a fun project too. I personally like to delve into the advanced aspects of Typescript at the type-level but it's taking me a while to wrap my head around the rationale and the solution of Tartak.

Nice stuff! All the best 👋
